// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgyrszcoctfqqxblewpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneXJzemNvY3RmcXF4Ymxld3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzYxODAsImV4cCI6MjA2NDU1MjE4MH0.9SBAT45RyPR2j4LamBcbjN_ZFsiYsm6P_QbAUpshZgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);